version: '3.9'

services:
  monetization_db:
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - monetization_db:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}

#  monetization:
#    container_name: monetization
#    build:
#      context: .
#      dockerfile: docker/monetization.Dockerfile
#    env_file:
#      - .env.dev.monetization
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#      monetization_db:
#        condition: service_healthy
#    ports:
#      - "8000:8000"

  rabbitmq:
    ports:
      - "${MQ_PORT}:5672"
      - "15672:15672"
      - "4369:4369"
      - "25672:25672"
  redis:
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_dev:/data

volumes:
  monetization_db:
  redis_dev:
