"""verification_token_table

Revision ID: 1e46606ecc56
Revises: 4f1f6dab0495
Create Date: 2023-12-05 10:19:33.378125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e46606ecc56'
down_revision = '4f1f6dab0495'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_token',
    sa.Column('user_email', sa.String(), nullable=False, comment='User email of the linked channel'),
    sa.Column('token', sa.String(), nullable=False, comment='Token'),
    sa.Column('id', sa.UUID(), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Creation date'),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Modified date'),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_token')
    # ### end Alembic commands ###
