"""subscriptions

Revision ID: cfeca4624c4a
Revises: 1e46606ecc56
Create Date: 2024-01-17 15:52:58.756239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfeca4624c4a'
down_revision = '1e46606ecc56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('user_email', sa.String(), nullable=False, comment='User email'),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False, comment='Paid user or not'),
    sa.Column('subscription_start', sa.DateTime(), nullable=False, comment='Date-Time when the subscription started'),
    sa.Column('subscription_expiry', sa.DateTime(), nullable=False, comment='Date-Time on which the subscription expires'),
    sa.Column('id', sa.UUID(), nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Creation date'),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Modified date'),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('verification_token', 'user_email',
               existing_type=sa.VARCHAR(),
               comment='User email',
               existing_comment='User email of the linked channel',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_token', 'user_email',
               existing_type=sa.VARCHAR(),
               comment='User email of the linked channel',
               existing_comment='User email',
               existing_nullable=False)
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
